services:
    tf2:
        build: .
        network_mode: "host"
        working_dir: /app/classified
        #volumes:
            #- ./maps:/app/classified/tf2classified/maps
            #- ./cfg:/app/classified/tf2classified/cfg
        #environment:
            #- MAXPLAYERS=32
